/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author henry
 */
import javax.swing.ButtonGroup;
import javax.swing.SwingUtilities;
public class RecipeGUI extends javax.swing.JFrame {
    
        private ButtonGroup radioButtonGroup;


    /**
     * Creates new form RecipeGUI
     */
    public RecipeGUI() {
        initComponents();
        
     TipsBtn = new javax.swing.JButton();
        
    radioButtonGroup = new ButtonGroup();
    MeatBtn = new javax.swing.JRadioButton("Meat Meal");
    VegetarianBtn = new javax.swing.JRadioButton("Vegetarian Meal");
    VeganBtn = new javax.swing.JRadioButton("Vegan Meal");
    
    radioButtonGroup.add(MeatBtn);
    radioButtonGroup.add(VegetarianBtn);
    radioButtonGroup.add(VeganBtn);
    
    
    
    getContentPane().setBackground(new java.awt.Color(176, 21, 78));
    
    Info.setBackground(new java.awt.Color(221, 166, 58));
    Info.setForeground(new java.awt.Color(255, 255, 255)); 

    
    RecipeBox.setBackground(new java.awt.Color(221, 166, 58));
    RecipeBox.setForeground(new java.awt.Color(255,255,255)); 
    
    TipsBtn.setBackground(new java.awt.Color(51, 51, 51)); 
    TipsBtn.setForeground(new java.awt.Color(255, 255, 255)); 

    FarmsBtn.setBackground(new java.awt.Color(51, 51, 51)); 
    FarmsBtn.setForeground(new java.awt.Color(255, 255, 255)); 

    ArticleBtn.setBackground(new java.awt.Color(51, 51, 51));
    ArticleBtn.setForeground(new java.awt.Color(255, 255, 255));

    RecipeBtn.setBackground(new java.awt.Color(51, 51, 51)); 
    RecipeBtn.setForeground(new java.awt.Color(255, 255, 255)); 
    
    



    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        FarmsBtn = new javax.swing.JButton();
        ArticleBtn = new javax.swing.JButton();
        RecipeBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Info = new javax.swing.JTextArea();
        MeatBtn = new javax.swing.JRadioButton();
        VegetarianBtn = new javax.swing.JRadioButton();
        VeganBtn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecipeBox = new javax.swing.JTextArea();
        TipsBtn = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FarmsBtn.setText("Farms");

        ArticleBtn.setText("Article");

        RecipeBtn.setText("Recipes");

        Info.setColumns(20);
        Info.setRows(5);
        Info.setText("This is the section on recipes which will be\nfocused around economic sustainability and \nmaking sure the ingredients used are fresh \nand locally sourced. \nThere will be 3 recipes - a meat meal, a \nvegetarian meal, and a vegan meal");
        jScrollPane2.setViewportView(Info);

        MeatBtn.setText("Meat Meal");
        MeatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeatBtnActionPerformed(evt);
            }
        });

        VegetarianBtn.setText("Vegetarian Meal");
        VegetarianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegetarianBtnActionPerformed(evt);
            }
        });

        VeganBtn.setText("Vegan Meal");
        VeganBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeganBtnActionPerformed(evt);
            }
        });

        RecipeBox.setColumns(20);
        RecipeBox.setRows(5);
        RecipeBox.setText("TIPS FOR EATING SUSTAINABLY\n\n1. EAT MORE PLANTS\nFarming animals for meat and dairy requires space and huge amounts of water and feed. \nThe livestock industry alone generates nearly 15% of all man made greenhouse gas emissions. \nWith global meat consumption soaring 500% between 1992 and 2016, it is clear we need to rebalance our diets by prioritising plants and moderating our intake of animal products. \n\n2. EAT MORE VARIETY\n75% of the world’s food supply comes from just 12 plants and five animal species. \nGreater diversity in our diets is essential as the lack of variety in agriculture is both bad for nature and a threat to food security. \n\n3. CUT THE WASTE\nFood waste is a big problem. 30% of the food produced is wasted, with serious repercussions for the environment. \nIn fact, if food waste was a country it would be the 3rd largest emitter of greenhouse gasses after China and the USA.  \nReducing waste in your household is simple: freeze anything you can’t eat while it’s fresh and, where possible, buy loose produce so you can select the exact amount that you need.\n\n4. GROW YOUR OWN FOOD\nWhat’s better than fresh, home-grown produce straight from the garden? \nAs well as being healthy and delicious, it is free from the carbon footprint of shop-bought food.\n\n5. PASS ON PLASTIC\nPlastic has infiltrated our natural world and even our diets. \nBring a reusable-bag when you shop, opt for packaging-free fruit and vegetables where possible, and ask brands and retailers that continue to use plastic to find alternatives.\n\n6. EAT WHAT’S IN SEASON\nWhen possible try to include seasonal produce from your local farm shop or greengrocer in your diet. \nAs well as supporting your local economy, you might get to know local producers and get tips on how to prepare seasonal foods.");
        jScrollPane1.setViewportView(RecipeBox);

        TipsBtn.setText("Tips !");
        TipsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(FarmsBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ArticleBtn)
                        .addGap(18, 18, 18)
                        .addComponent(RecipeBtn)
                        .addGap(424, 424, 424)
                        .addComponent(TipsBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(VeganBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VegetarianBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MeatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(110, 110, 110))))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FarmsBtn)
                    .addComponent(ArticleBtn)
                    .addComponent(RecipeBtn)
                    .addComponent(TipsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(MeatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VegetarianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VeganBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

// recipes have been taken from https://www.therealmealdeal.com/ and are basic recipes on each type of meal
    private void VeganBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeganBtnActionPerformed
        RecipeBox.setText("VEGAN SWEET POTATO CHILLI\n" +
"\n" +
"\n" +
"INGREDIENTS:\n" +
"-Sweet Potatoes	- Smoked paprika	-Cumin\n" +
"-2 Red Onions		-3 Red Peppers		-2 Garlic cloves\n" +
"-Chilli powder		-Chopped Tomatoes	-Kidney beans\n" +
"1. Preheat the oven to 200°C \n" +
"2. Pour half the oil in a large roasting dish and add the diced sweet potato. Sprinkle with half the sweet smoked paprika and cumin and turn over a few times to make sure the potato \n" +
"is coated. Roast for 25 minutes until cooked through.\n" +
"3. Add the rest of the olive oil to a frying pan and fry the onions, peppers and garlic over a medium heat for 5 minutes.\n" +
"4. Add the chilli powder, remaining ground cumin and sweet smoked paprika, Stir and fry for a further 1 minute. to release the flavours.\n" +
"5. Add the chopped tomatoes, drained and rinsed beans, oregano and season with salt and pepper. Bring to a boil then turn down the heat and simmer for 25 - 30 minutes.\n" +
"6. When the sweet potatoes are soft, stir them in to the chilli. Serve with the soured cream, sliced avocado and a few coriander leaves sprinkled over the top.\n" +
"\n" +
"\n" +
"SUSTAINABILITY:\n" +
"\n" +
"Try to buy your vegetables lose without any plastic packaging where possible and from a local source to reduce your food miles\n" +
"Also try buying vegan friendly zero-waste products with as little packaging as possible\n" +
"");
// TODO add your handling code here:
    }//GEN-LAST:event_VeganBtnActionPerformed

    private void VegetarianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegetarianBtnActionPerformed
        RecipeBox.setText("QUORN COTTAGE PIE\n" +
"\n" +
"\n" +
"INGREDIENTS:					EQUIPMENT:\n" +
"-Quorn Mince		-Potatoes			-Casserole Dish\n" +
"-Chopped Tomatoes	-Tomato Puree/Paste		-Frying Pan\n" +
"-Worchestershire Sauce	-Onions			\n" +
"-Carrots		-Vegetable Stock\n" +
"\n" +
"1. Preheat the oven to 200°C \n" +
"2. Peel potatoes and chop into cube pieces. Boil for 10 minutes until soft and then mash using some butter/milk (or both)\n" +
"3. Add oil to the pan and fry the onions and carrots over a medium heat until soft (around 5 minutes)\n" +
"4. Add Quorn mince to the pan and fry for around 5 minutes stirring occasionally.\n" +
"5. Pour over the tinned tomatoes, vegetable stock and worchestershire sauce. Season with salt and pepper and let simmer for 5 minutes.\n" +
"6. Transfer to an ovenproof casserole dish. Use a spoon and cover the mixture of mince and veg with a layer of mashed potatoes. (start at the outside and work inwards).\n" +
"7.Bake in the oven for 15-20 minutes until the potato is browned on the top. If you want to serve it with any additional veg such as peas or sweetcorn put these on to cook \n" +
"while the pie is in the oven\n" +
"\n" +
"\n" +
"\n" +
"SUSTAINABILITY:\n" +
"\n" +
"Try to buy your vegetables lose without any plastic packaging where possible and from a local source to reduce your food miles\n" +
"Quorn has a much lower carbon footprint than mince as it uses 90% less land, water and carbon emissions than animal proteins.\n" +
"");
        // TODO add your handling code here:
    }//GEN-LAST:event_VegetarianBtnActionPerformed

    private void MeatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeatBtnActionPerformed
        RecipeBox.setText("CHICKEN AND BROCCOLI PASTA BAKE\n" +
"\n" +
"INGREDIENTS:					EQUIPMENT:\n" +
"-Pasta	-Cream Cheese			-Large Frying Pan\n" +
"-Chicken	-Breadcrumbs				-Oven proof baking dish\n" +
"-Broccoli	-Cheese\n" +
"-Leeks	-Milk\n" +
"-Pesto	-Garlic\n" +
"\n" +
"1. Preheat the oven to 190°C and cook the pasta in a pan of lightly salted water intil its almost done.\n" +
"    Add the broccoli to the pasta for the last 5 minutes - the pasta and broccoli should be slightly undercooked as it will cook more in the oven\n" +
"2. Heat the oil in a large frying pan and if you are using fresh chicken, fry until browned then set aside. Leftover chicken is a good idea too if you have any to spare.\n" +
"3. Fry the leek over a medium heat for about 5 minutes, then add the garlic and fry for a further 2 minutes.\n" +
"4. Add the cream cheese, milk, and pesto (optional) to the pan and stir until melted.\n" +
"5. Add the chicken, pasta, and broccoli back to the pan and stir together so the pasta is well coated in the sauce. Season with salt and freshly ground black pepper.\n" +
"6. Tip into an oven-proof casserole dish and sprinkle the grated or shredded cheese and breadcrumbs over the top.\n" +
"    Bake in the oven for 20 - 25 minutes until the sauce is bubbling and the cheese is browned\n" +
"\n" +
"Once pasta bake is cooked, let it rest for 5 minutes before serving to allow it to firm up and the pasta will continue to absorb the sauce.\n" +
"\n" +
"SUSTAINABILITY:\n" +
"When buying meat, if you can, try to choose meat that has been bred as free-range and preferably from a local source. This will reduce the carbon footprint of the meat.\n" +
"Free-range or organic meat has higher animal welfare standards and a lower enviromental impact that industrially produced meats.\n" +
"Buy vegetables loose without any packaging and try to ensure they are from local sources. For example broccoli is available all year round but between October and April its in \n" +
"season and you may be able to find a greater amount of locally grown fresh broccoli during this period.\n" +
"\n" +
"");
        // TODO add your handling code here:
    }//GEN-LAST:event_MeatBtnActionPerformed
    
    
    private void TipsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipsBtnActionPerformed
        RecipeBox.setText("TIPS FOR EATING SUSTAINABLY\n" +
"\n" +
"1. EAT MORE PLANTS\n" +
"Farming animals for meat and dairy requires space and huge amounts of water and feed. \n" +
"The livestock industry alone generates nearly 15% of all man made greenhouse gas emissions. \n" +
"With global meat consumption soaring 500% between 1992 and 2016, it is clear we need to rebalance our diets by prioritising plants and moderating our intake of animal products. \n" +
"\n" +
"2. EAT MORE VARIETY\n" +
"75% of the world’s food supply comes from just 12 plants and five animal species. \n" +
"Greater diversity in our diets is essential as the lack of variety in agriculture is both bad for nature and a threat to food security. \n" +
"\n" +
"3. CUT THE WASTE\n" +
"Food waste is a big problem. 30% of the food produced is wasted, with serious repercussions for the environment. \n" +
"In fact, if food waste was a country it would be the 3rd largest emitter of greenhouse gasses after China and the USA.  \n" +
"Reducing waste in your household is simple: freeze anything you can’t eat while it’s fresh and, where possible, buy loose produce so you can select the exact amount that you need.\n" +
"\n" +
"4. GROW YOUR OWN FOOD\n" +
"What’s better than fresh, home-grown produce straight from the garden? \n" +
"As well as being healthy and delicious, it is free from the carbon footprint of shop-bought food.\n" +
"\n" +
"5. PASS ON PLASTIC\n" +
"Plastic has infiltrated our natural world and even our diets. \n" +
"Bring a reusable-bag when you shop, opt for packaging-free fruit and vegetables where possible, and ask brands and retailers that continue to use plastic to find alternatives.\n" +
"\n" +
"6. EAT WHAT’S IN SEASON\n" +
"When possible try to include seasonal produce from your local farm shop or greengrocer in your diet. \n" +
"As well as supporting your local economy, you might get to know local producers and get tips on how to prepare seasonal foods.");// TODO add your handling code here:
    }//GEN-LAST:event_TipsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArticleBtn;
    private javax.swing.JButton FarmsBtn;
    private javax.swing.JTextArea Info;
    private javax.swing.JRadioButton MeatBtn;
    private javax.swing.JTextArea RecipeBox;
    private javax.swing.JButton RecipeBtn;
    private javax.swing.JButton TipsBtn;
    private javax.swing.JRadioButton VeganBtn;
    private javax.swing.JRadioButton VegetarianBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
